title: scan-py
description: Sequential change-point detection with adaptive nonparametric inference
theme: jekyll-theme-minimal
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: default
